[".config/zsh/completions/_pip"]
  refreshPeriod = "168h"
  type = "file"
  url = "https://gist.githubusercontent.com/blueyed/54a257c411310a28805a/raw/_pip.zsh"

[".config/zsh/completions/_pyenv"]
  refreshPeriod = "168h"
  type = "file"
  url = "https://gist.githubusercontent.com/mgoodness/aa4026fa154ee859e661a0d8f0999361/raw/_pyenv.zsh"

[".gnupg/gpg.conf"]
  refreshPeriod = "168h"
  type = "file"
  url = "https://raw.githubusercontent.com/drduh/config/master/gpg.conf"

[".ssh/drduh_config"]
  refreshPeriod = "168h"
  type = "file"
  url = "https://raw.githubusercontent.com/drduh/config/master/ssh_config"
