[".config/bat/themes"]
type = "archive"
url = "https://github.com/catppuccin/bat/archive/main.tar.gz"
exact = true
stripComponents = 2
refreshPeriod = "168h"
include = ["*/themes/*.tmTheme"]

[".config/eza/themes"]
type = "archive"
url = "https://github.com/catppuccin/eza/archive/main.tar.gz"
exact = true
stripComponents = 2
refreshPeriod = "168h"
include = ["*/themes/**"]

[".config/ghostty/themes"]
type = "archive"
url = "https://github.com/catppuccin/ghostty/archive/main.tar.gz"
exact = true
stripComponents = 2
refreshPeriod = "168h"
include = ["*/themes/*.conf"]

[".config/helix/themes"]
type = "archive"
url = "https://github.com/catppuccin/helix/archive/main.tar.gz"
exact = true
stripComponents = 3
refreshPeriod = "168h"
include = ["*/themes/default/*.toml"]
