#!/bin/bash
# shellcheck shell=bash
# Minimal script to bootstrap https://chezmoi.io before it clones our dotfiles

set -euo pipefail
command -v bash &>/dev/null || { echo >&2 "ERROR: bash must be installed!" && exit 1; }
command -v git &>/dev/null || { echo >&2 "ERROR: git must be installed!" && exit 1; }

# Prompt for and remember password
echo "Prompting for sudo password"
sudo --validate
while true; do
    sudo -n true
    sleep 60
    kill -0 "$$" || exit
done &>/dev/null &

# On macOS, the default git needs CLT. Let brew install them headlessly.
if [ "$(uname)" = "Darwin" ] && ! [ -e "/Library/Developer/CommandLineTools/usr/bin/git" ]; then 
  echo "Installing homebrew..."
  NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

echo "Installing chezmoi..."
brew install chezmoi

echo "Bootstrapping dotfiles..."
chezmoi init --apply mgoodness