[env]
GH_HOST = "github.com"
GH_TOKEN = { value = "{{ exec(command='op read --account my.1password.com \"op://Private/GH CLI PAT/credential\"', cache_duration='8h', cache_key='personal-gh-token') }}" }
