[auto_update]
cooldown_days = 7

[[repos]]
repo = "https://github.com/frnmst/md-toc"
rev = "9.0.0"
hooks = [{ id = "md-toc", args = ["--in-place", "--skip-lines=1", "github"] }]

[[repos]]
repo = "https://github.com/codespell-project/codespell"
rev = "v2.4.2"
hooks = [{ id = "codespell", args = ["--ignore-words-list=protols,flate"] }]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "fish_indent"
name = "fish_indent"
entry = "fish_indent --write"
language = "system"
types = ["fish"]

[[repos.hooks]]
id = "oxfmt"
name = "oxfmt"
entry = "oxfmt --no-error-on-unmatched-pattern"
language = "system"
types = ["text"]
