[[repos]]
repo = "builtin"
hooks = [{ id = "end-of-file-fixer" }, { id = "trailing-whitespace" }]

[[repos]]
repo = "https://github.com/shellcheck-py/shellcheck-py"
rev = "v0.11.0.1"
hooks = [
  { id = "shellcheck", exclude_types = [
    "zsh",
  ] }, # https://github.com/koalaman/shellcheck/issues/809
]

[[repos]]
repo = "https://github.com/frnmst/md-toc"
rev = "9.0.0"
hooks = [{ id = "md-toc", args = ["--in-place", "--skip-lines=1", "github"] }]

[[repos]]
repo = "https://github.com/gitleaks/gitleaks"
rev = "v8.30.1"
hooks = [{ id = "gitleaks" }]

[[repos]]
repo = "https://github.com/codespell-project/codespell"
rev = "v2.4.2"
hooks = [{ id = "codespell", args = ["--ignore-words-list=protols"] }]

[[repos]]
repo = "https://github.com/zizmorcore/zizmor-pre-commit"
rev = "v1.24.1"
hooks = [{ id = "zizmor", args = ["--no-progress", "--fix=all"] }]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "fish_indent"
name = "fish_indent"
entry = "fish_indent --write"
language = "rust"
additional_dependencies = ["cli:https://github.com/fish-shell/fish-shell:4.7.1:fish"]
types = ["fish"]

[[repos.hooks]]
id = "shfmt"
name = "shfmt"
entry = "shfmt --indent=4 --write --keep-padding"
language = "golang"
language_version = "1.26"
additional_dependencies = ["mvdan.cc/sh/v3/cmd/shfmt@v3.13.1"]
types = ["shell"]

[[repos.hooks]]
id = "oxfmt"
name = "oxfmt"
entry = "oxfmt --no-error-on-unmatched-pattern"
language = "node"
additional_dependencies = ["oxfmt@0.48.0"]
types = ["text"]

[[repos]]
repo = "meta"
hooks = [{ id = "check-hooks-apply" }, { id = "check-useless-excludes" }]
