[auto_update]
cooldown_days = 7

[[repos]]
hooks = [{ id = "md-toc", args = ["--in-place", "--skip-lines=1", "github"] }]
repo = "https://github.com/frnmst/md-toc"
rev = "9.0.0"

[[repos]]
hooks = [{ id = "codespell", args = ["--ignore-words-list=protols,flate"] }]
repo = "https://github.com/codespell-project/codespell"
rev = "v2.4.2"

[[repos]]
repo = "local"

[[repos.hooks]]
entry = "fish_indent --write"
id = "fish_indent"
language = "system"
name = "fish_indent"
types = ["fish"]

[[repos.hooks]]
entry = "oxfmt --no-error-on-unmatched-pattern"
id = "oxfmt"
language = "system"
name = "oxfmt"
types = ["text"]

[[repos.hooks]]
entry = "bash -c 'for f in \"$@\"; do jq --sort-keys . \"$f\" | sponge \"$f\"; done' --"
exclude = "^dot_config/zed/"
id = "sort-json"
language = "system"
name = "sort-json"
types = ["json"]

[[repos.hooks]]
entry = "bash -c 'for f in \"$@\"; do yq --inplace \"sort_keys(..)\" \"$f\"; done' --"
id = "sort-yaml"
language = "system"
name = "sort-yaml"
types = ["yaml"]

[[repos.hooks]]
entry = "taplo fmt --option reorder_keys=true"
id = "sort-toml"
language = "system"
name = "sort-toml"
types = ["toml"]
