#!/usr/bin/env bash

local namespace namespaces fzf_query

namespaces=$(kubectl get namespaces -o name|cut -d/ -f2)

[[ -n "$@" ]] && fzf_query="--query=$@"
namespace=$(printf $namespaces | fzf --no-multi $fzf_query)
[[ -n "$namespace" ]] && kubectl config set-context --current --namespace="$namespace"
