#!/usr/bin/env bash

local fzf_query project projects

projects=$(gcloud projects list --format='table(name,project_id)')
[[ -n "$@" ]] && fzf_query="--query=$@"
project=$(printf $projects | fzf --header-lines=1 --no-multi $fzf_query)

gcloud config configurations create "$(printf $project | cut -f1 -d' ')"
gcloud config set core/project "$(printf $project | tr -s ' ' | cut -f2 -d' ')"
gcloud config set core/account michael.goodness@mlb.com
gcloud config set compute/region us-central1
gcloud config set compute/zone us-central1-a
