#!/usr/bin/env bash

VAULT_ADDR="https://vault-npd.shared.mlbinfra.net"

[[ "$1" == "prod" ]] && VAULT_ADDR="https://vault.shared.mlbinfra.net"

export VAULT_ADDR

vault login -no-print -method=oidc role=admin
