confirmQuit: false
defaults:
  issuesLimit: 20
  layout:
    issues:
      assignees:
        hidden: true
        width: 20
      createdAt:
        width: 5
      creator:
        width: 10
      creatorIcon:
        hidden: false
      repo:
        width: 15
      updatedAt:
        width: 5
    prs:
      assignees:
        hidden: true
        width: 20
      author:
        width: 15
      authorIcon:
        hidden: false
      base:
        hidden: true
        width: 15
      createdAt:
        width: 5
      labels:
        hidden: true
        width: 22
      lines:
        width: 15
      repo:
        width: 20
      updatedAt:
        width: 5
  notificationsLimit: 20
  prApproveComment: LGTM
  preview:
    height: 0.6
    open: true
    position: auto
    width: 0.45
  prsLimit: 20
  refetchIntervalMinutes: 30
  view: prs
includeReadNotifications: true
issuesSections:
  - filters: is:open author:@me
    title: My Issues
  - filters: is:open assignee:@me
    title: Assigned
  - filters: is:open involves:@me -author:@me
    title: Involved
keybindings: {}
notificationsSections:
  - filters: ""
    title: All
  - filters: reason:author
    title: Created
  - filters: reason:participating
    title: Participating
  - filters: reason:mention
    title: Mentioned
  - filters: reason:review-requested
    title: Review Requested
  - filters: reason:assign
    title: Assigned
  - filters: reason:subscribed
    title: Subscribed
  - filters: reason:team-mention
    title: Team Mentioned
pager:
  diff: ""
prSections:
  - filters: is:open author:@me
    title: My Pull Requests
  - filters: is:open review-requested:@me
    title: Needs My Review
  - filters: is:open involves:@me -author:@me
    title: Involved
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
repoPaths: {}
showAuthorIcons: true
smartFilteringAtLaunch: true
theme:
  ui:
    sectionsShowCount: true
    table:
      compact: false
      showSeparator: true
