# Ref: https://codeberg.org/jsu/dotfiles/src/branch/main/prek/global-hooks.toml

[auto_update]
cooldown_days = 7

[[repos]]
repo = "builtin"
hooks = [
  { id = "check-added-large-files", priority = 0 },
  { id = "check-case-conflict", priority = 0 },
  { id = "check-executables-have-shebangs", priority = 0 },
  { id = "check-illegal-windows-names", priority = 0 },
  { id = "check-json5", priority = 0 },
  { id = "check-merge-conflict", args = [
    "--assume-in-merge",
  ], priority = 0 },
  { id = "check-shebang-scripts-are-executable", priority = 0 },
  { id = "check-symlinks", priority = 0 },
  { id = "check-toml", priority = 0 },
  { id = "check-vcs-permalinks", priority = 0 },
  { id = "check-xml", priority = 0 },
  { id = "check-yaml", exclude = "/templates/", priority = 0 },
  { id = "destroyed-symlinks", priority = 0 },
  { id = "detect-private-key", priority = 0 },
  { id = "end-of-file-fixer" },
  { id = "fix-byte-order-marker" },
  { id = "mixed-line-ending" },
  { id = "trailing-whitespace" },
]

[[repos]]
repo = "meta"
hooks = [{ id = "check-hooks-apply" }, { id = "check-useless-excludes" }]

[[repos]]
repo = "https://github.com/betterleaks/betterleaks"
rev = "v1.3.1"
hooks = [{ id = "betterleaks", priority = 0 }]

[[repos]]
repo = "https://github.com/zizmorcore/zizmor-pre-commit"
rev = "v1.25.2"
hooks = [{ id = "zizmor", args = ["--no-progress", "--fix=all"] }]

[[repos]]
repo = "https://github.com/shellcheck-py/shellcheck-py"
rev = "v0.11.0.1"
hooks = [
  { id = "shellcheck", exclude = ".*\\.tmpl$", exclude_types = [
    "zsh",
  ] }, # https://github.com/koalaman/shellcheck/issues/809
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "shfmt"
name = "shfmt"
entry = "shfmt --indent=4 --write --keep-padding"
language = "system"
types = ["shell"]
exclude = ".*\\.tmpl$"
