[env]
GH_HOST = "github.com"
GH_TOKEN = { value = "{{ exec(cache_duration='1d', cache_key='emu-gh-token', command='op read --account mlb.1password.com \"op://Employee/EMU GH CLI PAT/credential\"') }}" }

[tools]
terraform = "latest"
terraform-docs = "latest"
