[env]
GH_HOST = "github.com"
GH_TOKEN = { value = "{{ exec(command='op read --account mlb.1password.com \"op://Employee/EMU GH CLI PAT/credential\"', cache_duration='8h', cache_key='emu-gh-token') }}" }

[tools]
terraform = "latest"
terraform-docs = "latest"
