# rubocop:disable Style/FrozenStringLiteralComment
# rubocop:disable Style/NumericLiterals
# rubocop:disable Style/StringLiterals

tap "beeftornado/rmtree", trusted: true
tap "dmtrkovalenko/fff", trusted: true

brew "bash"
brew "bat"
brew "bun"
brew "chezmoi"
brew "coreutils"
brew "curl"
brew "dmtrkovalenko/fff/fff-mcp", trusted: true
brew "dockutil"
brew "eza"
brew "fd"
brew "fish", args: ["HEAD"]
brew "fzf"
brew "gh"
brew "go"
brew "git-delta"
brew "git"
brew "gnu-sed"
brew "gnu-tar"
brew "grep"
brew "helix", args: ["HEAD"]
brew "httpie"
brew "jq"
brew "just"
brew "lazygit"
brew "less"
brew "mas"
brew "mise"
brew "mosh"
brew "node"
brew "oxfmt"
brew "parallel"
brew "pkgx"
brew "prek"
brew "ptpython"
brew "ripgrep"
brew "ruby"
brew "sd"
brew "shellcheck"
brew "shfmt"
brew "sponge"
brew "taplo"
brew "trash"
brew "tree"
brew "uv"
brew "viddy"
brew "vivid"
brew "wget"
brew "worktrunk"
brew "yq"
brew "zoxide"

cask "1password-cli@beta"
cask "1password@beta"
cask "betterdisplay"
cask "caffeine"
cask "claude-code@latest"
cask "claude"
cask "discord"
cask "font-fira-code-nerd-font"
cask "font-fira-code"
cask "gcloud-cli"
cask "ghostty"
cask "rectangle"

go "github.com/alexastrum/skl"

# krew "config-cleanup"
# krew "get-all"
# krew "support-bundle"

mas "1Password for Safari", id: 0
mas "AdBlock", id: 1402042596
mas "Developer", id: 640199958
mas "Keynote", id: 361285480
mas "Numbers", id: 361304891
mas "Pages", id: 361309726
mas "TestFlight", id: 899247664
mas "Xcode", id: 497799835

# rubocop:enable Style/FrozenStringLiteralComment
# rubocop:enable Style/NumericLiterals
# rubocop:enable Style/StringLiterals
