tap "beeftornado/rmtree"
tap "hashicorp/tap"
tap "homebrew/core"
tap "rossnicholson/tap"

brew "argocd"
brew "bash"
brew "bat"
brew "chezmoi"
brew "cocoapods"
brew "coreutils"
brew "curl"
brew "delve"
brew "dockutil"
brew "duti"
brew "eza"
brew "fd"
brew "fish", args: ["HEAD"]
brew "fzf"
brew "gemini-cli"
brew "gh"
brew "git-delta"
brew "git"
brew "gnu-sed"
brew "gnu-tar"
brew "go"
brew "goreleaser"
brew "grep"
brew "hashicorp/tap/vault"
brew "helix", args: ["HEAD"]
brew "helm"
brew "httpie"
brew "jfrog-cli"
brew "jq"
brew "krew"
brew "ksops"
brew "kubernetes-cli"
brew "kustomize"
brew "lazygit"
brew "less"
brew "mas"
brew "mise"
brew "parallel"
brew "pkgx"
brew "prek"
brew "ripgrep"
brew "sd"
brew "skaffold"
brew "sops"
brew "trash"
brew "uv"
brew "viddy"
brew "vivid"
brew "wget"
brew "worktrunk"
brew "yq"
brew "zoxide"

cask "1password-cli"
cask "1password"
cask "akuity"
cask "betterdisplay"
cask "caffeine"
cask "claude-code"
cask "claude"
cask "cmux"
cask "copilot-cli"
cask "discord"
cask "flutter"
cask "font-fira-code-nerd-font"
cask "font-fira-code"
cask "gcloud-cli"
cask "macdive"
cask "rectangle"
cask "rossnicholson/tap/clawdbar"
cask "slack"
cask "zed"

krew "config-cleanup"
krew "get-all"
krew "support-bundle"

mas "1Password for Safari", id: 1569813296
mas "AdBlock", id: 1402042596
mas "Developer", id: 640199958
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Okta Extension App", id: 1439967473
mas "Okta Verify", id: 490179405
mas "Pages", id: 409201541
mas "Submersion", id: 6757456915
mas "TestFlight", id: 899247664
mas "Xcode", id: 497799835
