[env]
CLOUDSDK_ACTIVE_CONFIG_NAME = "mlb"
GH_ENTERPRISE_TOKEN = { value = "{{ exec(cache_duration='7d', cache_key='mlbam-gh-token', command='/opt/homebrew/bin/fnox get GH_ENTERPRISE_TOKEN') }}" }
GH_HOST = "github.mlbam.net"
