name: CI

on:
  push:
    paths-ignore: ["**.md"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  bootstrap:
    runs-on: macos-latest
    steps:
      - run: sh -c "$(curl -fsLS get.chezmoi.io/lb)" -- init --apply --branch=${GITHUB_REF_NAME} mgoodness
