name: prek auto-update

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions: {}

jobs:
  auto-update:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0 # zizmor: ignore[unpinned-uses]
        with:
          persist-credentials: false
      - run: |
          pipx run prek autoupdate
          pipx run prek autoupdate --config dot_config/prek/global-hooks.toml
      - uses: peter-evans/create-pull-request@v8.1.1 # zizmor: ignore[unpinned-uses]
        with:
          branch: prek-autoupdate
          commit-message: "chore(prek): autoupdate hook revisions"
          delete-branch: true
          title: "chore(prek): autoupdate hook revisions"
